logging:
  file: log/collect.log
  config: classpath:logback.xml

spring:
  datasource:
#    url: jdbc:sqlite:D:\\wrapper\\lib\\collect.db
    url: jdbc:sqlite:D:\zw\test\sqlitedbtmp\路由监控\\monitor.db
    driver-class-name: org.sqlite.JDBC

  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 9084
  compression:
    min-response-size: 512
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain,text/css,application/x-javascript



mybatis-plus:
  type-aliases-package: com.jcca.entity
  mapper-locations: classpath:/mapper/*.xml
  # 驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    # 打印sql
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


route:
  ip: 192.168.59.1
  telnet-port: 23
  #用户名
  user: cisco
  #登录密码
  password: Pwd@1234
  #特权密码
  password2: cisco
  #采集端口
  interface-name: Serial0/1/0:0
  #采集周期毫秒数
  interval-ms: 10000





